In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/municipal_main.csv')
df.head()

,ID,AGS,ARS,GEN,lan_name,east_west,fuaname_core,fuaname_comm,KFL_2021,bs_2005,...,Discontinous_low_dense_urban_2018,Isolated_strcutures_2018,Discontinous_dense_urban_2018,Green_urban_area_2018,Industrial_commercial_2018,Discontinous_medium_dense_urban_2018,Discontinous_very_low_dense_urban_2018,Land_no_current_use_2018,Fast_transit_roads_2018,Airports_2018
0,1,1051001.0,1.051518e+10,Albersdorf,Schleswig-Holstein,West,NaN,NaN,17.12,422018.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,1051002.0,1.051518e+10,Arkebek,Schleswig-Holstein,West,NaN,NaN,6.92,45613.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,1051003.0,1.051516e+10,Averlak,Schleswig-Holstein,West,NaN,NaN,9.06,95403.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1051004.0,1.051518e+10,Bargenstedt,Schleswig-Holstein,West,NaN,NaN,11.90,156547.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1051005.0,1.051517e+10,Barkenholm,Schleswig-Holstein,West,NaN,NaN,5.11,36667.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.shape

(10995, 100)

In [4]:
grid = pd.read_csv('data/100m_grid.csv')
grid.head()

,OID_,livespace_pp_2022,bs_2005,bs_20,pop_05,pop_20,lupp05,lupp20,vac_2022,x_map,y_map
0,0,58.34,NaN,1188.0,NaN,5.35099,NaN,222.014999,NaN,4147550,2716250
1,1,28.62,NaN,189.0,NaN,1.21886,NaN,155.061996,NaN,4146150,2716350
2,2,40.90,NaN,1402.0,NaN,12.08740,NaN,115.988998,NaN,4147650,2716450
3,3,60.54,NaN,720.0,NaN,2.89465,NaN,248.735001,NaN,4147750,2716550
4,4,12.37,324.0,2096.0,5.3816,20.76630,60.205101,100.932999,NaN,4145450,2716650

In [5]:
grid.shape

(2554606, 11)

In [7]:
grid[grid.bs_2005.notna()]

,OID_,livespace_pp_2022,bs_2005,bs_20,pop_05,pop_20,lupp05,lupp20,vac_2022,x_map,y_map
4,4,12.37,324.0,2096.0,5.38160,20.76630,60.205101,100.932999,NaN,4145450,2716650
6,6,62.14,845.0,886.0,8.48052,8.34115,99.640099,106.220001,NaN,4146650,2716750
7,7,44.36,1003.0,1021.0,10.43810,9.96785,96.090301,102.429001,NaN,4146750,2716750
8,8,28.72,1006.0,1020.0,9.91008,9.42706,101.513001,108.198998,NaN,4146950,2716750
9,9,86.67,343.0,904.0,3.09200,7.64894,110.931000,118.185997,NaN,4147050,2716750
...,...,...,...,...,...,...,...,...,...,...,...
2554600,2554600,65.13,141.0,864.0,NaN,2.25140,NaN,383.760986,NaN,4541450,3512650
2554601,2554601,51.68,416.0,1311.0,1.43779,3.41671,289.334015,383.701996,NaN,4541550,3512750
2554602,2554602,98.72,579.0,1148.0,2.00184,2.99145,289.234009,383.760986,NaN,4541650,3512750
2554603,2554603,96.68,640.0,644.0,2.21198,1.67813,289.334015,383.760986,NaN,4538350,3512850
2554604,2554604,66.87,688.0,1018.0,2.37788,2.65269,289.334015,383.760986,NaN,4541750,3512950

In [8]:
grid.sample(10000).to_csv('data/sample_100m_grid.csv', index=False)

In [10]:
CampusFile_HK_cities = pd.read_csv('data/panel/CampusFile_HK_cities.csv')
CampusFile_HK_cities.shape

/var/folders/46/ky7ff4bj6874xpchl1bc9cqh0000gn/T/ipykernel_6952/3668904833.py:1: DtypeWarning: Columns (1,10,19) have mixed types. Specify dtype option on import or set low_memory=False.
  CampusFile_HK_cities = pd.read_csv('data/panel/CampusFile_HK_cities.csv')

(390296, 71)

In [11]:
CampusFile_HK_cities.sample(10000).to_csv('data/sample_CampusFile_HK_cities.csv', index=False)

In [12]:
CampusFile_WK_cities = pd.read_csv('data/panel/CampusFile_WK_cities.csv')
CampusFile_WK_cities.shape

/var/folders/46/ky7ff4bj6874xpchl1bc9cqh0000gn/T/ipykernel_6952/704301620.py:1: DtypeWarning: Columns (1,11,21) have mixed types. Specify dtype option on import or set low_memory=False.
  CampusFile_WK_cities = pd.read_csv('data/panel/CampusFile_WK_cities.csv')

(986641, 72)

In [13]:
CampusFile_WK_cities.sample(10000).to_csv('data/sample_CampusFile_WK_cities.csv', index=False)

In [14]:
CampusFile_WM_cities = pd.read_csv('data/panel/CampusFile_WM_cities.csv')
CampusFile_WM_cities.shape

/var/folders/46/ky7ff4bj6874xpchl1bc9cqh0000gn/T/ipykernel_6952/1619228265.py:1: DtypeWarning: Columns (1,11,19) have mixed types. Specify dtype option on import or set low_memory=False.
  CampusFile_WM_cities = pd.read_csv('data/panel/CampusFile_WM_cities.csv')

(4755938, 70)

In [15]:
CampusFile_WM_cities.sample(10000).to_csv('data/sample_CampusFile_WM_cities.csv', index=False)

In [16]:
CampusFile_HK_2023 = pd.read_csv('data/cross_section/CampusFile_HK_2023.csv')
CampusFile_HK_2023.shape

/var/folders/46/ky7ff4bj6874xpchl1bc9cqh0000gn/T/ipykernel_6952/2754969325.py:1: DtypeWarning: Columns (1,10,48) have mixed types. Specify dtype option on import or set low_memory=False.
  CampusFile_HK_2023 = pd.read_csv('data/cross_section/CampusFile_HK_2023.csv')

(350359, 70)

In [17]:
CampusFile_HK_2023.sample(10000).to_csv('data/sample_CampusFile_HK_2023.csv', index=False)

In [18]:
CampusFile_WK_2023 = pd.read_csv('data/cross_section/CampusFile_WK_2023.csv')
CampusFile_WK_2023.shape

/var/folders/46/ky7ff4bj6874xpchl1bc9cqh0000gn/T/ipykernel_6952/516394945.py:1: DtypeWarning: Columns (1,11) have mixed types. Specify dtype option on import or set low_memory=False.
  CampusFile_WK_2023 = pd.read_csv('data/cross_section/CampusFile_WK_2023.csv')

(165473, 71)

In [19]:
CampusFile_HK_2023.sample(10000).to_csv('data/sample_CampusFile_WK_2023.csv', index=False)

In [20]:
CampusFile_WM_2023 = pd.read_csv('data/cross_section/CampusFile_WM_2023.csv')
CampusFile_WM_2023.shape

/var/folders/46/ky7ff4bj6874xpchl1bc9cqh0000gn/T/ipykernel_6952/527346494.py:1: DtypeWarning: Columns (1,11) have mixed types. Specify dtype option on import or set low_memory=False.
  CampusFile_WM_2023 = pd.read_csv('data/cross_section/CampusFile_WM_2023.csv')

(372842, 69)

In [21]:
CampusFile_WM_2023.sample(10000).to_csv('data/sample_CampusFile_WM_2023.csv', index=False)