In [11]:
import os, sys
PROJECT_ROOT = os.path.abspath(os.path.join(os.getcwd(), '..'))
sys.path.append(PROJECT_ROOT)

In [12]:
import pandas as pd
from utils import *

In [13]:
df_ = pd.read_csv('predicted_data_3.csv')

In [14]:
df = df_.copy()
df.head()

,obid,plz,mietekalt,wohnflaeche,etage,zimmeranzahl,schlafzimmer,badezimmer,aufzug,balkon,...,objektzustand,blid,rent_sqm,is_schlafzimmer_imputed,is_parkplatz_imputed,year,month,predicted_mietekalt,difference,perc_change
0,41534430,22587,918.00,114.700000,1,4.0,1.0,1.0,0,1,...,Completely renovated,Hamburg,8.003488,False,True,2007,5,1089.37,171.37,0.19
1,42410574,20251,374.33,48.000000,1,2.0,1.0,1.0,0,1,...,Well-kept,Hamburg,7.798541,False,True,2007,7,363.76,-10.57,-0.03
2,38404913,22303,565.60,74.000000,4,3.0,1.0,1.0,0,0,...,Well-kept,Hamburg,7.643243,False,True,2007,6,583.24,17.64,0.03
3,41026870,22765,284.00,40.410000,4,2.0,1.0,1.0,1,1,...,Like new,Hamburg,7.027964,False,True,2007,3,324.52,40.52,0.14
4,36771732,20357,373.00,55.439999,2,2.0,1.0,1.0,0,0,...,Not specified,Hamburg,6.727994,False,True,2007,7,394.10,21.10,0.06

In [22]:
agg_df = (
    df
    .groupby(['year', 'month', 'blid'])
    .agg(
        mean_actual=('mietekalt', 'mean'),
        mean_predicted=('predicted_mietekalt', 'mean'),
        mean_difference=('difference', 'mean'),
        median_difference=('difference', 'median'),
        std_difference=('difference', 'std'),
        count=('difference', 'count')
    )
    .reset_index()
).round(2)

In [23]:
agg_df

,year,month,blid,mean_actual,mean_predicted,mean_difference,median_difference,std_difference,count
0,2007,1,Baden-Wuerttemberg,545.00,569.86,24.86,22.52,41.14,10
1,2007,1,Bavaria,545.03,557.11,12.07,5.73,81.97,46
2,2007,1,Berlin,447.79,464.49,16.70,12.80,52.81,64
3,2007,1,Free Hanseatic City of Bremen,454.29,473.31,19.03,16.88,20.27,7
4,2007,1,Hamburg,499.00,514.71,15.71,12.01,48.31,37
...,...,...,...,...,...,...,...,...,...
1895,2023,12,Hamburg,1101.24,1095.55,-5.68,4.24,150.32,732
1896,2023,12,Hesse,1248.56,1242.00,-6.56,0.00,97.35,1691
1897,2023,12,Lower Saxony,794.15,785.29,-8.87,-0.43,81.56,464
1898,2023,12,North Rhine-Westphalia,797.62,795.79,-1.83,9.83,127.43,3713
1899,2023,12,The Free State of Saxony,725.34,713.37,-11.97,-1.84,68.37,1722

In [24]:
agg_df.to_excel('agg_predicted_data.xlsx', index=False)